name: "JSON Key Value Check Action"
description: "Check that JSON Key's Values Match Provided Values"
author: "Shane"
branding:
  icon: "code"
  color: "green"

inputs:
  file:
    description: "JSON File"
    required: true
  keys:
    description: "Keys to Check"
    required: true
  values:
    description: "Values to Verify"
    required: true
  seperator:
    description: "Nested Key Seperator"
    required: false
    default: "."

outputs:
  result:
    description: "JSON Output Results"

runs:
  using: "node20"
  main: "dist/index.js"
